package scripting.idlescript.AIOQuester.models;

import java.util.Arrays;
import models.entities.ItemId;
import models.entities.Location;
import models.entities.QuestId;
import models.entities.SkillId;
import scripting.idlescript.AIOQuester.quests.*;

// TODO: Add support for UIMs in quests requiring banked items
// TODO: Add descriptions for last few QuestDefs in Quest enum

// While mini-quests can be added to requiredQuests there is no way to check them via controller.
// If the only missing requirement for a quest is the mini-quest, the quest can be started.
// You must add checking for the miniquest in its corresponding quest script.

public enum Quest {
  BLACK_KNIGHTS_FORTRESS(
      new QuestDef(
          "Black Knight's Fortress",
          QuestId.BLACK_KNIGHTS_FORTRESS.getId(),
          false,
          "The black knights are up to no good. You are hired by the white knights to spy on them and uncover their evil scheme.",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          12,
          null)),
  COOKS_ASSISTANT(
      new QuestDef(
          "Cook's Assistant",
          QuestId.COOKS_ASSISTANT.getId(),
          false,
          "The lumbridge castle cook is in a mess. It is the duke of Lumbridge's birthday and the cook is making the cake. He needs a lot of ingredients and doesn't have much time.",
          1,
          Location.LUMBRIDGE_CASTLE_COURTYARD,
          null,
          null,
          null,
          null,
          null,
          4,
          0,
          CooksAssistant.class)),
  DEMON_SLAYER(
      new QuestDef(
          "Demon Slayer",
          QuestId.DEMON_SLAYER.getId(),
          false,
          "A mighty demon is being summoned to destroy the city of Varrock. You find out you are the one destined to stop him.",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  DORICS_QUEST(
      new QuestDef(
          "Doric's Quest",
          QuestId.DORICS_QUEST.getId(),
          false,
          "Doric the dwarf is happy to let you use his anvils but first he would like you to run an errand for him.",
          1,
          Location.FALADOR_WEST_BANK,
          null,
          new int[][] {{SkillId.MINING.getId(), 15}},
          null,
          null,
          null,
          13,
          0,
          DoricsQuest.class)),
  THE_RESTLESS_GHOST(
      new QuestDef(
          "The Restless Ghost",
          QuestId.THE_RESTLESS_GHOST.getId(),
          false,
          "A ghost is haunting Lumbridge graveyard. The priest of the Lumbridge church of Saradomin wants you to find out how to get rid of it.",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  GOBLIN_DIPLOMACY(
      new QuestDef(
          "Goblin Diplomacy",
          QuestId.GOBLIN_DIPLOMACY.getId(),
          false,
          "There's a disturbance in the goblin village. Help the goblins solve their dispute so the world doesn't have to worry about rioting goblins.",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  ERNEST_THE_CHICKEN(
      new QuestDef(
          "Ernest the Chicken",
          QuestId.ERNEST_THE_CHICKEN.getId(),
          false,
          "Veronica is very worried. Her fiancee went into the big spooky manor house to ask for directions. An hour later and he's still not out yet.",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  IMP_CATCHER(
      new QuestDef(
          "Imp Catcher",
          QuestId.IMP_CATCHER.getId(),
          false,
          "The Wizard Grayzag has summoned hundreds of little imps. They have stolen a lot of things belonging to the Wizard Mizgog including his magic beads.",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  PIRATES_TREASURE(
      new QuestDef(
          "Pirate's Treasure",
          QuestId.PIRATES_TREASURE.getId(),
          false,
          "Redbeard Frank knows where secret pirate treasure is hidden, it may require some work to persuade him to let you know where though.",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  PRINCE_ALI_RESCUE(
      new QuestDef(
          "Prince Ali Rescue",
          QuestId.PRINCE_ALI_RESCUE.getId(),
          false,
          "Prince Ali of Al Kharid has been kidnapped by the scheming Lady Keli. You are hired to stage a rescue mission.",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  ROMEO_AND_JULIET(
      new QuestDef(
          "Romeo and Juliet",
          QuestId.ROMEO_AND_JULIET.getId(),
          false,
          "Romeo & Juliet are desperately in love, but Juliet's father doesn't approve. Help them to find a way to get married and live happily ever after.",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  SHEEP_SHEARER(
      new QuestDef(
          "Sheep Shearer",
          QuestId.SHEEP_SHEARER.getId(),
          false,
          "Farmer Fred's sheep are getting mighty woolly. He will pay you to shear them.",
          1,
          Location.LUMBRIDGE_CASTLE_COURTYARD,
          null,
          null,
          null,
          null,
          null,
          21,
          0,
          SheepShearer.class)),
  SHIELD_OF_ARRAV(
      new QuestDef(
          "Shield of Arrav",
          QuestId.SHIELD_OF_ARRAV.getId(),
          false,
          "Varrocian literature tells of a valuable shield stolen from long ago the museum of Varrock by a gang of professional thieves. See if you can track down this shield and return it to the museum. You will need a friend to help you complete this quest.",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  THE_KNIGHTS_SWORD(
      new QuestDef(
          "The Knight's Sword",
          QuestId.THE_KNIGHTS_SWORD.getId(),
          false,
          "Sir Vyvin's squire is in trouble. He has lost Sir Vyvin's ceremonial sword. Help him find a replacement without Sir Vyvin finding out.",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  VAMPIRE_SLAYER(
      new QuestDef(
          "Vampire Slayer",
          QuestId.VAMPIRE_SLAYER.getId(),
          false,
          "The people of Draynor village live in constant terror. Their numbers are dwindling, all due to the foul creature lurking in the manor to the north known as a vampire.",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  WITCHS_POTION(
      new QuestDef(
          "Witch's Potion",
          QuestId.WITCHS_POTION.getId(),
          false,
          "Become one with your darker side. Tap into your hidden depths of magical potential by making a potion with the help of Hetty the Rimmington witch.",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  DRAGON_SLAYER(
      new QuestDef(
          "Dragon Slayer",
          QuestId.DRAGON_SLAYER.getId(),
          false,
          "Prove yourself a true hero. Kill the mighty dragon Elvarg of Crandor Island and earn the right to buy and wear the powerful rune plate mail body.",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          32,
          null)),
  WITCHS_HOUSE(
      new QuestDef(
          "Witch's House",
          QuestId.WITCHS_HOUSE.getId(),
          false,
          "A young boy who lives in Taverley has kicked his ball into the garden of a scary old lady. He asks you to get it back for him. This proves more difficult than it first sounds.",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  LOST_CITY(
      new QuestDef(
          "Lost City",
          QuestId.LOST_CITY.getId(),
          false,
          "Legends tell of a magical lost city hidden in the swamps. Many adventurers have tried to find this city, but it is proving difficult. Can you unlock the secrets of the city of Zanaris?",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  HEROS_QUEST(
      new QuestDef(
          "Hero's Quest",
          QuestId.HEROS_QUEST.getId(),
          false,
          "Prove you are worthy to enter the hero's guild. To prove your status as a hero you will need to obtain a number of items. There are many challenges standing between you and these items.",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          55,
          null)),
  DRUIDIC_RITUAL(
      new QuestDef(
          "Druidic Ritual",
          QuestId.DRUIDIC_RITUAL.getId(),
          false,
          "To start using the herblaw skill you will need to ask for some training from the druids. However they require some help with a ritual before they will help you.",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  MERLINS_CRYSTAL(
      new QuestDef(
          "Merlin's Crystal",
          QuestId.MERLINS_CRYSTAL.getId(),
          false,
          "Merlin the wizard has carelessly become imprisoned inside a giant crystal. Take up king Arthur's quest to free Merlin and become one of the knights of the round table.",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  BARCRAWL(
      new QuestDef(
          "Alfred Grimhand Bar Crawl",
          -1,
          true,
          "Add a quest description here",
          -1,
          Location.BARBARIAN_OUTPOST_ENTRANCE,
          null,
          null,
          new int[][] {{ItemId.COINS.getId(), 1000}},
          null,
          null,
          5,
          0,
          BarCrawl.class)),
  SCORPION_CATCHER(
      new QuestDef(
          "Scorpion Catcher",
          QuestId.SCORPION_CATCHER.getId(),
          false,
          "Thormac has lost his rare lesser kharid scorpions after leaving their cage door open. These scorpions have hidden in areas that are rather difficult to get into. You will have to overcome various challenges (and drink a lot of beer) to get all the scorpions back If you manage to help him Thormac will improve your battle staffs.",
          2,
          Location.SORCERERS_TOWER_F1,
          new Quest[] {BARCRAWL},
          new int[][] {{SkillId.PRAYER.getId(), 31}, {SkillId.AGILITY.getId(), 70}},
          new int[][] {{ItemId.COINS.getId(), 1000}},
          new int[][] {{ItemId.ANTI_DRAGON_BREATH_SHIELD.getId(), 1}},
          null,
          5,
          0,
          ScorpionCatcher.class)),
  FAMILY_CREST(
      new QuestDef(
          "Family Crest",
          QuestId.FAMILY_CREST.getId(),
          false,
          "The Fitzharmon family crest has gone missing, and the family honour has been lost. Can you find the crest and return it to Dimintheis in Varrock? There are 3 different rewards available, but you can only choose one, so choose carefully!",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  TRIBAL_TOTEM(
      new QuestDef(
          "Tribal Totem",
          QuestId.TRIBAL_TOTEM.getId(),
          false,
          "Lord Handelmort of Ardougne is collector of exotic artifacts. A recent addition to his private collection is a strange looking totem from Karamja. The Rantuki tribe are not happy about the recent disappearance of their totem.",
          2,
          Location.ARDOUGNE_SOUTH_BANK,
          null,
          new int[][] {{SkillId.THIEVING.getId(), 21}},
          new int[][] {{ItemId.COINS.getId(), 1000}},
          null,
          null,
          5,
          0,
          TribalTotem.class)),
  FISHING_CONTEST(
      new QuestDef(
          "Fishing Contest",
          QuestId.FISHING_CONTEST.getId(),
          false,
          "The mountain Dwarves home would be an ideal way to get across White Wolf mountain safely. However the Dwarves aren't to fond of strangers. They will let you through if you can bring them a trophy. The trophy is the prize for the annual Hemenster fishing competition.",
          3,
          Location.CATHERBY_DWARF_TUNNEL,
          null,
          new int[][] {{SkillId.FISHING.getId(), 10}},
          new int[][] {{ItemId.COINS.getId(), 1000}},
          null,
          null,
          10,
          0,
          FishingContest.class)),
  MONKS_FRIEND(
      new QuestDef(
          "Monk's Friend",
          QuestId.MONKS_FRIEND.getId(),
          false,
          "A monk's child has had their blanket stolen. Find the thieves' den and return the blanket, then help Brother Omad organise the drinks for the child's birthday party.",
          4,
          Location.ARDOUGNE_MONASTERY,
          null,
          null,
          new int[][] {{ItemId.BRONZE_AXE.getId(), 1}},
          null,
          null,
          5,
          0,
          MonksFriend.class)),
  TEMPLE_OF_IKOV(
      new QuestDef(
          "Temple of Ikov",
          QuestId.TEMPLE_OF_IKOV.getId(),
          false,
          "A mysterious stranger called Lucien asks you to go on a mission deep under the Temple of Ikov in central Kandarin. He wants you to retrieve an artifact known as the Staff of Armadyl. Towards the end of the quest you are presented with a choice on how to complete the quest.",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  CLOCK_TOWER(
      new QuestDef(
          "Clock Tower",
          QuestId.CLOCK_TOWER.getId(),
          false,
          "Help the confused Brother Kojo find the missing cogs and fix his watch tower. Search the dungeon using brawn and brains to correctly place the four cogs.",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  THE_HOLY_GRAIL(
      new QuestDef(
          "The Holy Grail",
          QuestId.THE_HOLY_GRAIL.getId(),
          false,
          "King Arthur is sending out his knights on a quest for the famous holy grail. If you are a knight of the round table go to king Arthur for further orders.",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  FIGHT_ARENA(
      new QuestDef(
          "Fight Arena",
          QuestId.FIGHT_ARENA.getId(),
          false,
          "The prosperous Servil family have been abducted by the infamous General Khazard. He plans to have the family battle for his entertainment in the fight arena. Can you rescue the Servil's before the tyrant has these innocent (not to mention wealthy) civilians slain.",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  TREE_GNOME_VILLAGE(
      new QuestDef(
          "Tree Gnome Village",
          QuestId.TREE_GNOME_VILLAGE.getId(),
          false,
          "The tree gnomes are in trouble. General Khazard's forces are hunting them to extinction. Find you way through the hedge maze to the gnomes secret treetop village. Then help the gnomes fight Khazard and retrieve the orbs of protection.",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  THE_HAZEEL_CULT(
      new QuestDef(
          "The Hazeel Cult",
          QuestId.THE_HAZEEL_CULT.getId(),
          true,
          "Discover the truth behind the Carnillean family fortune. Decide for yourself whether to aid the Carnilleans in retrieving stolen goods, or join the Hazeel cult members in their mission to resurrect the infamous Lord Hazeel.",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  SHEEP_HERDER(
      new QuestDef(
          "Sheep Herder",
          QuestId.SHEEP_HERDER.getId(),
          false,
          "Some plague infected sheep have escaped into East Ardounge. They must be found and disposed off before the whole town is infected, time is of the essence.",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  PLAGUE_CITY(
      new QuestDef(
          "Plague City",
          QuestId.PLAGUE_CITY.getId(),
          false,
          "A shadow of disease has overcast Ardounge. Edmond's daughter Elena has gone missing in West Ardougne whilst trying to help the plague victims there. See if you can find out what's going on.",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  SEA_SLUG(
      new QuestDef(
          "Sea Slug",
          QuestId.SEA_SLUG.getId(),
          false,
          "Something strange is happening on the fishing platform. Missing fishermen and the presence of dozens of strange sea creatures gives cause for concern. Investigate the platform, discover the truth before it's too late.",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  WATERFALL_QUEST(
      new QuestDef(
          "Waterfall Quest",
          QuestId.WATERFALL_QUEST.getId(),
          false,
          "Investigate the death of elven leaders of old. Search for the elf king Baxtorian's tomb and discover the mysterious hidden treasure of the waterfall.",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  BIOHAZARD(
      new QuestDef(
          "Biohazard",
          QuestId.BIOHAZARD.getId(),
          false,
          "Second part of an ongoing adventure. Help Elena discover the truth about the infamous Ardounge plague. Smuggle test samples across Ardounge to Elena's old mentor.",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  JUNGLE_POTION(
      new QuestDef(
          "Jungle Potion",
          QuestId.JUNGLE_POTION.getId(),
          false,
          "Trufitus Shakaya of the Tai Bwo Wannai Village requires that you collect five special jungle herbs for a potion so he can commune with his Gods.",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  GRAND_TREE(
      new QuestDef(
          "Grand Tree",
          QuestId.GRAND_TREE.getId(),
          false,
          "The Grand Tree, which shelters the majority of RuneScape's small gnome population, is dying. Is it human sabotage or an inside job? Help King Shareem to find the true cause and save the tree gnomes from an uncertain fate.",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  SHILO_VILLAGE(
      new QuestDef(
          "Shilo Village",
          QuestId.SHILO_VILLAGE.getId(),
          false,
          "New areas in the Southern part of Karamja Island have been discovered with a mysterious village. Who knows what hidden treasures exist, and what dangers lurk to guard them?",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  UNDERGROUND_PASS(
      new QuestDef(
          "Underground Pass",
          QuestId.UNDERGROUND_PASS.getId(),
          false,
          "The Underground Pass, sealed for thousands of years, has now been reopened to reveal a complex labyrinth of tunnels and chasms. You must find a way through, and get one step closer to the evil King Tyras. But the road is long and it could be lonely. When fatigue starts to take it's toll, mental strength is what you'll need...",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  OBSERVATORY_QUEST(
      new QuestDef(
          "Observatory Quest",
          QuestId.OBSERVATORY_QUEST.getId(),
          false,
          "The observatory in South West Ardougne has been ransacked by a family of nearby goblins. Can you help the professors to rebuild it?\n\nUse your skills at crafting to make the various parts, and fight your way through the cavern under the observatory. Use the telescope and the stars hold a secret for you.",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  TOURIST_TRAP(
      new QuestDef(
          "Tourist Trap",
          QuestId.TOURIST_TRAP.getId(),
          false,
          "South of Al Kharid a new Desert Pass has opened up, leading to the dangers of the Kharid desert.\n\nDon your desert garb and make sure your waterskin is full before heading off into the trackless dunes in search of desert adventure.",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  WATCHTOWER(
      new QuestDef(
          "Watchtower",
          QuestId.WATCHTOWER.getId(),
          false,
          "The Wizards of the Yanille Watch Tower have been reporting increased ogre sightings recently. Use a wide variety of your skills to help the wizards recover their stolen power crystals and stop the advance of the ogre hordes!",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  DWARF_CANNON(
      new QuestDef(
          "Dwarf Cannon",
          QuestId.DWARF_CANNON.getId(),
          false,
          "For several years now the dwarven black guard have been developing the latest in projectile warfare. Now with the constant attack of goblin renegades, the dwarven troops who protect the mines need to put this secret weapon into action. Only with your help can the true power of this cannon be harnessed!",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  MURDER_MYSTERY(
      new QuestDef(
          "Murder Mystery",
          QuestId.MURDER_MYSTERY.getId(),
          false,
          "Lord Sinclair, a highly respected Nobleman of Kandarin has been found murdered in his mansion. Despite the presence of a large number of guards all working hard to solve the crime, local law enforcement officers are totally baffled.\n\nCan you use your razor sharp analytical mind to uncover the evidence and unmask the culprit?",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  DIGSITE(
      new QuestDef(
          "Digsite Quest",
          QuestId.DIGSITE.getId(),
          false,
          "Feeling uneducated? Desperate for buried treasure?\n\n...There's gold in them there hills (well stream actually) as well as many other items that can be found at the digsite.\n\nJoin the students in their attempt to be a qualified archaeologist, and become experienced in making the earth move!\n\nHave you got what it takes to unearth the hidden altar to one of Runescape's lesser-known Gods...?",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  GERTRUDES_CAT(
      new QuestDef(
          "Gertrude's Cat",
          QuestId.GERTRUDES_CAT.getId(),
          false,
          "Gertrude's cat has been missing for some time now - for her piece of mind her prized pet must be rescued.\n\nHandling cats isn't an easy business. They get hungry and need plenty of attention but if you're the pet type, then this is the quest for you!",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  LEGENDS_QUEST(
      new QuestDef(
          "Legend's Quest",
          QuestId.LEGENDS_QUEST.getId(),
          false,
          "Accept the challenge of the Legends Guild to map the Southern part of Karamja Island, make friends with the natives and bring back a prize to display in the Legends Guild Main Hall.",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          107,
          null)),
  RUNE_MYSTERIES(
      new QuestDef(
          "Rune Mysteries",
          QuestId.RUNE_MYSTERIES.getId(),
          false,
          "Recent research at the Wizards' Tower has found a way to create Runes for the first time in centuries. Assist the head wizard Sedridor in his research and he too may teach you these secrets!",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  PEELING_THE_ONION(
      new QuestDef(
          "Peeling the Onion",
          QuestId.PEELING_THE_ONION.getId(),
          false,
          "Add a quest description here",
          -1,
          null,
          null,
          null,
          null,
          null,
          null,
          -1,
          0,
          null)),
  ODYSSEY(
      new QuestDef(
          "The Odyssey",
          -1,
          true,
          "Add a quest description here",
          -1,
          null,
          new Quest[] {LEGENDS_QUEST},
          null,
          null,
          null,
          null,
          5,
          0,
          null));

  private final QuestDef quest;

  Quest(QuestDef quest) {
    this.quest = quest;
  }

  public QuestDef getQuestDef() {
    return quest;
  }

  public static QuestDef getQuestDefFromName(String name) {
    return Arrays.stream(Quest.values())
        .map(Quest::getQuestDef)
        .filter(q -> q.getName().equals(name))
        .findFirst()
        .orElse(null);
  }
}
